### ISSUE TITLE
Containers are not communicating with each other

### ISSUE THREAD

**Issue by nkkaushik** [aws/amazon-ecs-agent#1166]
### I have launched 3 different containers in one task definition on single instance and created service with one task only without any load balancer. My containers are not communicating with each other. 
1. I have tried bridge, default & awsvpc network types but no success
2. On the EC2 instance, I created one new bridge network but there is no way in task definition to mention the usage of the new bridge network and containers are always placed in the default bridge network only and that seem to have some issues.
3. When I launch my containers manually or using a script directly in EC2 container, all is fine. ECS seems to be a problem here.
4. I tried fargate also but it is kind of blackbox where we cannot even enter the instance and see what is going on. Fargate is expensive also hence not my cup of tea.

Please suggest how can I make my containers talk to each other using ECS.

**Comment by richardpen** [comment]
@nkkaushik Can you describe how these containers are trying to communicate with each other? Are you using the `links`(which is corresponding to the [docker links](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/) ) in your task definition?

**Comment by nkkaushik** [comment]
@richardpen yes, I am using links. However I got it working now after changing the links configuration. Container A needs to talk to container B and I had mentioned Container A in container definition of Container B and assumed that ECS would allow bi-directional communication but Container A was unable to talk to B. Then I changed container definition and reversed the links setting (by mentioning Container B in A's definition) and it worked.

Now I have two queries if you can help me:
1. How can I enable bidirectional communication between the containers in above mentioned scenario? I don't want to use any AWS load balancer
2. If I don't want to run my containers in default bridge network then is there any way to tell task definition to run the containers in user defined network?

Thanks for your help.

**Comment by richardpen** [comment]
> How can I enable bidirectional communication between the containers in above mentioned scenario? I don't want to use any AWS load balancer

We released [task networking feature](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html) back to Nov, where all the containers within the same task share the same network namespace so that container can talk to each other without modification. That should satisfy this scenario, though an additional ENI is required for each task.

> If I don't want to run my containers in default bridge network then is there any way to tell task definition to run the containers in user defined network?

Unfortunately, this isn't supported by ECS today, this is a feature request #437, please track that issue for further update.

Please let me know if you have further questions.

**Comment by nkkaushik** [comment]
Thanks @richardpen for your help 👍

**Comment by arjunlandes** [comment]
Hey @richardpen, I have the same problem and links does not seem to be working. Here is my [docker-compose file](https://github.com/lyft/amundsen/blob/master/docs/installation-aws-ecs/docker-ecs-amundsen.yml) that works locally and the containers communicate fine. My `ecs-params.yml` is:

```
version: 1
task_definition:
  services:
    neo4j:
      cpu_shares: 100
      mem_limit: 3GB
    elasticsearch:
      cpu_shares: 100
      mem_limit: 3GB
    amundsensearch:
      cpu_shares: 100
      mem_limit: 500MB
      links:
        - elasticsearch:elasticsearch
    amundsenmetadata:
      cpu_shares: 100
      mem_limit: 500MB   
      links:
        - neo4j:neo4j
    amundsenfrontend:
      cpu_shares: 100
      mem_limit: 500MB
      links:
        - amundsenmetadata:amundsenmetadata
        - amundsensearch:amundsensearch
```

I haven't been able to find much help on Google so far.

**Comment by corrjo** [comment]
> version: 1
> task_definition:
>   services:
>     neo4j:
>       cpu_shares: 100
>       mem_limit: 3GB
>     elasticsearch:
>       cpu_shares: 100
>       mem_limit: 3GB
>     amundsensearch:
>       cpu_shares: 100
>       mem_limit: 500MB
>       links:
>         - elasticsearch:elasticsearch
>     amundsenmetadata:
>       cpu_shares: 100
>       mem_limit: 500MB   
>       links:
>         - neo4j:neo4j
>     amundsenfrontend:
>       cpu_shares: 100
>       mem_limit: 500MB
>       links:
>         - amundsenmetadata:amundsenmetadata
>         - amundsensearch:amundsensearch

@arjunlandes did you ever figure this out? been banging my head against this for far too long.

**Comment by dgokcin** [comment]
@corrjo @arjunlandes hello I am having the same problem. have you managed to work around this?

**Comment by renanxx1** [comment]
@arjunlandes 
I'm facing the same problem. 
How did you manage to solve it?:

**Comment by dgokcin** [comment]
@renanxx1 after more investigation, I figured out that the containers were able to communicate with each other but there was a confiuration error with my front end. My frontend needs the url of my backend in a `.env` file and I configured it like `API_URL=backend` where backend is the service name in my compose file. This did not work since my browser has no idea what backend means. 

After figuring this out, I did a lot of magic with my build pipeline to create the network load balancer with awscli and extract its public endpoint to use it in the deployment stage of my pipeline. This way I managed to connect from my browser to the services deployed behind the network load balancer. Here is a snippet from my frontend build block
```yaml
      - name: Build & Push the App Container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache/fe
          cache-to: type=local,dest=/tmp/.buildx-cache/fe
          tags: |
            ${{ steps.image-names.outputs.app_image }}
          build-args: |
            NODE_BUILD=build-pg
            REACT_APP_API_ENDPOINT=http://${{ needs.create-loadbalancer.outputs.endpoint }}:5000
            REACT_APP_IDENTITY_ENDPOINT=http://${{ needs.create-loadbalancer.outputs.endpoint }}:5005
```

And here is a snippet from my compose file 
```yaml
x-aws-loadbalancer: ${LOADBALANCER_ARN}
version: "3.9"
services:
  backend:
    image: "${WEBAPI_IMAGE:-backend}"
    # ...
```

I also want to note that I can reach from my backend services to other backend services(where no browser is needed) by using networks keyword in my compose file. For instance, with the following config, my backend can communicate with redis using its service name.

```yaml
x-aws-loadbalancer: ${LOADBALANCER_ARN}
version: "3.9"
services:
  backend:
    image: "${WEBAPI_IMAGE:-backend}"
    build:
      context: ..
      dockerfile: ./docker/app.dockerfile
    ports:
      - "5000:5000"
    networks:
      - back-tier
      - default
  frontend:
    image: "${WEBAPP_IMAGE:-frontend}"
    build:
      context: ../../WebApp
      dockerfile: ./Dockerfile
    ports:
      - "80:80"

  identity:
    image: "${IDENTITY_IMAGE:-identity}"
    deploy:
      resources:
        reservations:
          memory: ${IDENTITY_MEMORY:-0.5G}
          cpus: ${IDENTITY_CPU:-0.25}
    build:
      context: ../../IdentityServer
      dockerfile: ./docker/app.dockerfile
    ports:
      - 5005:5005

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - back-tier

networks:
  back-tier:
```
I hope it helps :)
