### ISSUE TITLE
Deploy docker images on ECR between accounts?

### ISSUE THREAD

**Issue by Baxtex** [aws/amazon-ecs-agent#2053]
We have two aws accounts and environments, lets call them dev and prod. In dev we have a codepipeline that builds our code, creates a docker image and pushes it to the ECR of dev. This works great! Now we would like to setup some kind of integration between dev and prod. So  on a push of a button, the image from dev ecr is, in some way, deployed in prod. However, this seems to be cumbersome or I just don't understand how to implement it. What I have tried:

In prod:

1. Using codebuild. I have been able to setup an instance where it fetches the image from dev, but then I realized that it wanted to use that image for buildning, so that didn't work. I then continues to use a standard aws image and trying to pull and then push the image using the following build file:

```
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to dev ecr...
      - docker login -u AWS -p vdfgdshjfgds....
      - echo Pulling the Docker image...
      - docker pull 123.dkr.ecr.eu-west-1.amazonaws.com/app:latest
  build:
    commands:
  post_build:
    commands:
      - echo Logging into prod ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
      - echi Pusing image to diagnostics ecr..
      - docker push 999.dkr.ecr.eu-west-1.amazonaws.com/app:latest
      - printf '[{"name":"app","imageUri":"999.dkr.ecr.eu-west-1.amazonaws.com/app"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json

```
  Always fails on  unauthorized: incorrect username or password  though. I set the prod (999) account to have access to the repository on the dev ecr permission tab.

 2.CodePipeline, not much progress here, it does not seem to be possible to set an "external" ecr as a source. That would be ideal for me. 

 3.Deploy: Same thing as two, I cannot the the source to an external ecr. 

Edit I managed to solve it using number 1! I had to change my login like this:

      - echo Logging in to dev ecr...
      - output=$(aws ecr get-login --registry-ids 123 --region eu-west-1 --no-include-email)
      - $output
