### ISSUE TITLE
tmpfs and dev shm for Fargate

### ISSUE THREAD

**Issue by taktakpeops** [aws/amazon-ecs-agent#2324]
### Summary
This is more a question than an issue. I am currently trying to run a Selenium Grid with Chrome and Firefox node in ECS Fargate.

My container are able to start but all my tests are failing because `/dev/shm` cannot be set as in an ECS launch type.

I was wondering if `tmpfs` and `dev shm` will be accessible in Fargate at some point. If not, I would like to understand the why (which I believe is related to the architecture of Fargate).

### Description

Currently, for giving access to `/dev/shm` to my container inside a task, I am doing the following in my Cloudformation manifest:

```
SeleniumNodeChromeTask:
    Type: "AWS::ECS::TaskDefinition"
    DependsOn: TalpaAccountSeleniumGrid
    Properties:
      Volumes:
        - Name: "shm"
    ContainerDefinitions:
    - MountPoints:
           - ContainerPath: /dev/shm
              SourceVolume: shm
              ReadOnly: false
```

The volume is mounted correctly but Firefox and Chrome keep failing.

Here is an error message I got from my Firefox container:

```
WARNING: failed to open shm: Permission denied: file /builds/worker/workspace/build/src/ipc/chromium/src/base/shared_memory_posix.cc, line 250
```

### Expected Behavior
I am expecting to be able to setup tmpfs and dev shm for my container and get my headless browsers to work as expected

### Environment Details

ECS Cluster: latest
Selenium Grid Docker images: 3.141.59-yttrium (official images)
