### ISSUE TITLE
Container stuck in "Pending" if dependency not satisfied due to docker error

### ISSUE THREAD

**Issue by Trane9991** [aws/amazon-ecs-agent#2350]
The issue is similar to #2152:

### Summary
Container stuck in `Pending` state when container it depends on failed to start due to docker error.

### Description
Task has two containers A and B.
Container A depends on container B:
```
        DependsOn:
          - Condition: COMPLETE
            ContainerName: B
        VolumesFrom:
          - ReadOnly: true
            SourceContainer: B
```
However, for some reason container B failed to start `STOPPED (CannotStartContainerError: Error response from daemon)"`, (container just hangs in `Created` state with error: `"ExitCode": 128, "Error": "error while mounting volume '': get: no such volume"`).

### Expected Behavior
Task mark as failed and retried

### Observed Behavior
Container A stuck in `PENDING` state.

### Environment Details
ECS agent version v1.36.1
