### ISSUE TITLE
Bridge network between services - unknown hostname

### ISSUE THREAD

**Issue by rgfindl** [aws/amazon-ecs-agent#559]
I am trying to make inter-service http calls.  Here is a simplified setup.
```
version: '2'
services:
  servicea:
    environment:
      SERVICE_B_URL: 'http://serviceb:8181'
    links:
      - serviceb

  serviceb:
    environment:
      SERVICE_A_URL: 'http://servicea:2000'
```
Here is what I would expect to work because it works with docker-compose: 
servicea -> http://serviceb:8181
serviceb -> http://servicea:2000

When deployed to ECS:
servicea -> http://serviceb:8181 (Works!)
serviceb -> http://servicea:2000 (Hostname not found)

FYI...  If I remove the `link` the first call also fails.  

The following workaround, which uses the bridge ip, works:
```
version: '2'
services:
  servicea:
    environment:
      SERVICE_B_URL: 'http://serviceb:8181'
    links:
      - serviceb
    ports:
      - 2000:2000

  serviceb:
    environment:
      SERVICE_A_URL: 'http://172.17.0.1:2000'
```

Any idea how I can get the first example working?  Thanks!
