### ISSUE TITLE
Service that runs a task on each ECS host instance

### ISSUE THREAD

**Issue by cjbottaro** [aws/amazon-ecs-agent#828]
Hello,

Currently to accomplish this, I'm doing this:

```
desired_count: 1000 # Something much higher than number of instances in cluster
placement_constraints:
  - type: distinctInstance
placement_strategy:
  - type: spread
    field: instanceId
```

Does this put unnecessary load on the agent or instance?  I see in the web ui a bunch of events like:
```
service datadog_agent was unable to place a task because no container instance met all of its requirements.
```

Is that ok to just let this go on indefinitely?  If not, how to accomplish the goal of having a service that runs a task once on each ECS instance in the cluster?

Thanks.
