### ISSUE TITLE
Auto Scaling desired count

### ISSUE THREAD

**Issue by optimisticanshul** [aws/amazon-ecs-agent#862]
Here is my scalable target which says minimum capacity of 2 but still auto scaling changed my count to 0.
```
    ScalableTarget:
        Type: AWS::ApplicationAutoScaling::ScalableTarget
        DependsOn: Service
        Properties:
          MaxCapacity: 4
          MinCapacity: 2
          ResourceId: !Join [ '/', ['service', !Ref Cluster, !Ref ServiceName]]
          RoleARN: !Ref AutoscaleRoleARN
          ScalableDimension: ecs:service:DesiredCount
          ServiceNamespace: ecs
```

Message: Successfully set desired count to 0. Change successfully fulfilled by ecs. Cause: monitor alarm prod-xxx-svc-MemoryAlarmLow-10J4RTUH8WRH0 in state ALARM triggered policy prod-xxx-svc-scale-down
